
#%RAML 1.0
---
title: Example API
description: This API retrieves account details.
version: v1
baseUri: https://api.example.com

securitySchemes:
  client_auth:
    description: client Authentication required
    type: x-custom

\accounts/{accountID}:
  get:
    securedBy: [client_auth]
    body:
      application/json:
        type: object
        properties:
            {}
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "financialAccountDetails": {
                  "account": {
                    "accountId": "10100075340880",
                    "identifier": {
                      "brId": "90354299",
                      "cifId": "1277392"
                    },
                    "accountType": "CA",
                    "accountTypeDesc": "Savings",
                    "currency": "CAD",
                    "balance": {
                      "current": 5741.32,
                      "hold": 0,
                      "available": 5741.32,
                      "availableCredit": 700.56,
                      "currency": "CAD"
                    },
                    "product": {
                      "productId": "AR.BUS.SAV.HIS",
                      "name": "Business Jumpstart HISA"
                    },
                    "branch": {
                      "identifier": {
                        "transitNumber": "15410"
                      },
                      "name": "Point Grey Branch",
                      "institution": {
                        "financial InstitutionId": "809",
                        "institutionType": {
                          "type": "SWIFT",
                          "value": "809"
                        },
                        "name": "Vancity"
                      }
                    },
                    "lendingDetails": {
                      "payment": {
                        "nextPayment DueDate": "2024-11-30T00:00:00"
                      },
                      "locLimit": {
                        "amount": 5000.0
                      }
                    },
                    "accountStatus": "Active",
                    "alias": "Toms Business Jumpstart Savings",
                    "openedDate": "2016-11-14T00:00:00",
                    "interestRates": [
                      {
                        "category": "Credit",
                        "rateMatrix": [
                          {
                            "rate": 2.3
                          }
                        ]
                      },
                      {
                        "category": "Debit",
                        "rateMatrix": [
                          {
                            "rate": 21
                          }
                        ]
                      }
                    ]
                  }
                }
              }
      400:
        body:
          application/json:
            example: |
              {
                "Code": "TGB-200",
                "Description": "Bad Request",
                "Details": {
                  "Code": "TGV-404",
                  "Description": "Account no is not valid"
                }
              }
